#!/bin/bash
function cube() {
	tmpval=$(($1*$1*$1))
	#echo $tmpval >/dev/null
	return $tmpval
}

count=0
value=0

while((count<10))
do
	cube $count
	printf "H triti dynami toy arithmou %d einai %d\n" $count $? 
	count=$((count+1))
done
